apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: xandersnelder/auth-service:latest
        command: ["python", "main.py", "auth_service"]
        ports:
        - containerPort: 3001
        env:
        - name: BASE_URL
          value: "http://auth-service:3001"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
      imagePullSecrets:
      - name: my-registry-secret