apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: xandersnelder/url-shortener:latest
        ports:
        - containerPort: 3000
        env:
        - name: BASE_URL
          value: "http://url-shortener:3000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        volumeMounts:
        - name: url-data
          mountPath: /app/url_data
      volumes:
      - name: url-data
        configMap:
          name: url-data
      imagePullSecrets:
      - name: my-registry-secret
