apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: xandersnelder/url-shortener:latest
          command: ["python", "main.py", "url_shortener"]
          ports:
            - containerPort: 3000
          env:
            - name: BASE_URL
              value: "http://url-shortener:3000"
          volumeMounts:
            - name: data-volume
              mountPath: /app/url_data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: url-data-pvc
