apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000